"""Index every finished run and its replay, for the record and for the Phase 9 bundles.

Writes `docs/RUNS.md` (committed: ids and numbers only, no review text) and
`data/replays/index.json` (gitignored, next to the replay files it lists). Showcase runs
are the curated set the demo and the methodology results are built from.

Usage (from backend/, with the API running on :8001):
    uv run python ../tools/run_index.py
"""

import json
import sys
from pathlib import Path

import httpx

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from app.core.config import settings  # noqa: E402

# Curated: the runs MEASUREMENTS M11 reports, and the earlier method versions for
# comparison. label -> run id.
SHOWCASE = {
    # current rules (M13), v4 answers reused from the runs below: what the demo shows
    "Helldivers 2 5K · current rules": "run_104cc1191ff8",
    "Borderlands 2 Apr-Aug 2025 · current rules": "run_31ffbd3bddd6",
    "Metro 2033 Redux Dec 2018-Mar 2019 · current rules": "run_e638053d0ca6",
    "Total War: ROME II Aug-Oct 2018 · v5": "run_e54638b2b2ce",
    "Football Manager 26 launch→now · current rules": "run_55d11443d036",
    "Cities: Skylines II 5K control · current rules": "run_696384d545ae",
    "Gollum control · current rules": "run_51d5d8355914",
    "Helldivers 2 5K · v4 three ratings": "run_32a69a6357c9",
    "Borderlands 2 Apr-Aug 2025 · v4 three ratings": "run_cb355add8483",
    "Metro 2033 Redux Dec 2018-Mar 2019 · v4 three ratings": "run_319a013d4535",
    "Football Manager 26 launch→now · v4 three ratings": "run_fe99d4915e40",
    "Cities: Skylines II 5K control · v4": "run_e22d6bb5a0b0",
    "Gollum control · v4": "run_862c7f603aac",
    "Helldivers 2 5K · v3 (about_game)": "run_e99fa4e93eb4",
    "Borderlands 2 · v3 (about_game)": "run_8df6975a69d8",
    "Helldivers 2 5K · v2 spec weights (length bias)": "run_f5c957411488",
    "Cities: Skylines II 5K · v2 spec weights": "run_28248c78172d",
    "Gollum · v2 spec weights": "run_b223491d0701",
}


def pct(v: float | None) -> str:
    return "—" if v is None else f"{100 * v:.1f}%"


def main() -> None:
    with httpx.Client(base_url="http://localhost:8001", timeout=60) as c:
        runs = c.get("/runs", params={"limit": 500}).json()
        datasets = {d["id"]: d for d in c.get("/datasets").json()}
    by_id = {r["id"]: r for r in runs}
    replays = settings.replays_dir
    rows, index = [], []
    for r in sorted(runs, key=lambda r: r.get("started_at") or ""):
        s = r.get("summary") or {}
        p = s.get("platform") or {}
        ds = datasets.get(r["dataset_id"], {})
        has_replay = (replays / f"{r['id']}.jsonl.gz").exists()
        entry = {
            "run_id": r["id"],
            "dataset_id": r["dataset_id"],
            "dataset": ds.get("name"),
            "backend": r["backend"],
            "question_set": r["config"].get("question_set"),
            "status": r["status"],
            "reviews": s.get("n_reviews"),
            "raw": s.get("raw"),
            "adjusted": s.get("adjusted"),
            "adjusted_ci": s.get("ci"),
            "platform": p.get("rating"),
            "platform_ci": p.get("ci"),
            "cost_usd": r.get("cost_usd"),
            "replay": f"data/replays/{r['id']}.jsonl.gz" if has_replay else None,
            "showcase": next((k for k, v in SHOWCASE.items() if v == r["id"]), None),
        }
        index.append(entry)
        rows.append(entry)
    missing = [k for k, v in SHOWCASE.items() if v not in by_id]
    if missing:
        sys.exit(f"showcase runs not found in the API: {missing}")

    (replays / "index.json").write_text(json.dumps(index, indent=1), encoding="utf-8")

    lines = [
        "# Runs",
        "",
        "Generated by `tools/run_index.py`. Ids and numbers only (no review text). Replay files live in",
        "`data/replays/<run_id>.jsonl.gz` (gitignored); `data/replays/index.json` lists them. **Do not",
        "delete them:** the Phase 9 public demo is built from these replays.",
        "",
        "## Showcase runs",
        "",
        "| Run | Id | Q-set | Reviews | Raw | Adjusted (95% CI) | Platform policy (95% CI) | Cost | Replay |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for label, rid in SHOWCASE.items():
        e = next(x for x in index if x["run_id"] == rid)
        ci = e["adjusted_ci"]
        pci = e["platform_ci"]
        lines.append(
            f"| {label} | `{rid}` | {e['question_set']} | {e['reviews']:,} | {pct(e['raw'])} | "
            f"{pct(e['adjusted'])} ({pct(ci[0]) if ci else '—'}-{pct(ci[1]) if ci else '—'}) | "
            f"{pct(e['platform'])}{f' ({pct(pci[0])}-{pct(pci[1])})' if pci else ''} | "
            f"${(e['cost_usd'] or 0):.3f} | {'✅' if e['replay'] else '❌'} |"
        )
    lines += [
        "",
        "## All runs",
        "",
        "| Id | Dataset | Backend | Q-set | Status | Reviews | Raw | Adjusted | Platform | Replay |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for e in index:
        lines.append(
            f"| `{e['run_id']}` | {e['dataset'] or e['dataset_id']} | {e['backend']} | {e['question_set']} | "
            f"{e['status']} | {e['reviews'] or '—'} | {pct(e['raw'])} | {pct(e['adjusted'])} | "
            f"{pct(e['platform'])} | {'✅' if e['replay'] else '❌'} |"
        )
    (ROOT / "docs" / "RUNS.md").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(
        f"{len(index)} runs indexed, {sum(1 for e in index if e['replay'])} with replays; showcase {len(SHOWCASE)}"
    )


if __name__ == "__main__":
    main()
